name: Build & Deploy Quartz Site
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  packages: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/littleomar/quartz-build:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: /app/quartz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Quartz
        run: echo $GITHUB_WORKSPACE && npx quartz build --directory=$GITHUB_WORKSPACE

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4